services:
  postgres:
    image: postgres:16
    container_name: prueba_reimagine_postgres
    environment:
      POSTGRES_DB: PruebaTecnicaReImagine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: